// See http://webpack.github.io/docs/configuration.html for webpack configuration options.

module.exports = {
  // 'context' sets the directory where webpack looks for module files you list in
  // your 'require' statements
  context: __dirname + '/app/assets/javascripts',

  // 'entry' specifies the entry point, where webpack starts reading all
  // dependencies listed and bundling them into the output file.
  // The entrypoint can be anywhere and named anything - here we are calling it
  // '_application' and storing it in the 'javascripts' directory to follow
  // Rails conventions.
  entry: './_application.js',

  // 'output' specifies the filepath for saving the bundled output generated by
  // wepback.
  // It is an object with options, and you can interpolate the name of the entry
  // file using '[name]' in the filename.
  // You will want to add the bundled filename to your '.gitignore'.
  output: {
    filename: '[name].bundle.js',
    path: __dirname + '/app/assets/javascripts',
  },

  externals: {
    // Make jQuery available via require("jquery").
    jquery: 'var jQuery'
  },

  // Add source maps.
  devtool: '#eval-source-map',

  // Configure webpack to use loaders.
  module: {
    loaders: [
      {
        // Transpiles es6 to es5.
        loader: 'es6-loader'
      }
    ]
  }
};
