// See http://webpack.github.io/docs/configuration.html for webpack configuration options.

module.exports = {
  // Specifies the entry point, where webpack starts reading all
  // dependencies listed and bundling them into the output file.
  context: __dirname,
  entry: "./app/assets/javascripts/app/hello_world",

  // Specifies the path for saving the bundled output generated by webpack.
  output: {
    path: __dirname + "/app/assets/javascripts",
    filename: "[name].bundle.js"
  },
  module: {
    loaders: [
      { test: /\.jsx$/, exclude: __dirname + /node_modules/, loader: "babel-loader" }
    ]
  },
  resolve: {
    root: __dirname + "/app/assets/javascripts/app",
    extensions: ["", ".webpack.js", ".web.js", ".js", ".jsx"]
  },
  devtool: "#eval-source-map"
};
